name: Simple Workflow

on:
  workflow_call:
    inputs:
      message:
        description: "Message to pass"
        required: true
        type: string

jobs:
  demo:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Run a marketplace action (checkout)
        uses: actions/checkout@v5

      - name: Run custom echo action
        uses: israoo/pipecraft-actions/.github/actions/echo-message@v1
        with:
          message: ${{ inputs.message }}
